# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DrawingApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DrawingApp
  pod 'RxSwift', '6.0'
  pod 'RxCocoa', '6.0'
  pod 'SnapKit'

  target 'DrawingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DrawingAppUITests' do
    # Pods for testing
  end

end
